apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
namePrefix: dev-
commonLabels:
  test: opsverse
commonAnnotations:
  test-annotation: opsverse

# images:
#   - name: quay.io/redhatworkshops/welcome-php
#     newName: differentregistry/myimage

replicas:
- name: welcome-php
  count: 2

resources:
- ../../base

# patchesStrategicMerge:
# - change-replicas.yaml
